### ISSUE TITLE
path & git information get truncated after a CMD + K

### ISSUE THREAD

**Issue by Sufiane** [sindresorhus/pure#452] opened 2018-12-05 11:12 UTC
### General information
Same issue as #329 
- Pure version: 1.x.x
- ZSH version: 5.x.x
- Terminal program & version: Hyper 2.0 & basic mac OS terminal 
- Operating system: macOs Mojave 10.14
- ZSH framework: oh-my-zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
It's actualy the same issue as #329 but removing oh-my-zsh doesn't work on my end, I still get the directory path swallowed.
The prompt get truncated when cleaning terminal screen (`CMD` + `k`), the path & git information are invisible.

### Reproduction steps

1. spam the terminal screen with commands or commands results
2. Hit `CMD` + `k`

### My `.zshrc`:

*I did not change anything from the installation*
```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment] 2018-12-05 18:24
Duplicate of #451. It seems Hyper has changed the implementation of Cmd+K since #329, it is no longer synonymous with Ctrl+L, which is why it doesn't work.

**Closed by mafredri** 2018-12-05 18:24 UTC

**Comment by Sufiane** [comment] 2018-12-05 19:52
My bad I did not check good enough the already open issues :/

I'll see with Hyper then !

Thanks for the quick reply and the dopeness of this prompt !
