### ISSUE TITLE
Pure with fzf

### ISSUE THREAD

**Issue by vaff** [sindresorhus/pure#327] opened 2017-05-29 12:52 UTC
I'm running the .oh-my-zsh zplug plugin and I have issues when I try to run pure and this script: https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236

That means I have fzf running. The error I'm getting is pretty consistent, it is:

```shell
prompt_pure_async_callback:10: bad set of key/value pairs for associative array
```

I'm just sourcing the files. I'm not good enough with Zsh to see if I'm doing a mistake or if it is pure or the scripts.

**Comment by mafredri** [comment] 2017-05-29 13:07
Does it also produce errors if you source the script(s) after the prompt has initialized? E.g. remove from zshrc and do it manually at the prompt.

**Comment by vaff** [comment] 2017-05-30 07:50
Hmn no, then the errors don't come. That means it is an error on my end?

**Comment by mafredri** [comment] 2017-05-30 08:05
Maybe, maybe not, I don't really have a lot go on here, but my hunch is that the fzf bindings are somehow messing with the Pure async worker.

Could you show me what lines you use to initialize this?

**Comment by vaff** [comment] 2017-05-30 15:51
I've only sourced them, then the error showed up. I've had fzf running without them (together with pure) fin.

**Comment by mafredri** [comment] 2017-05-30 15:53
To understand this problem better I need to know exactly what you're doing, I can somewhat guess but I would rather not. The gist you linked to does not give a clear picture of what that might be.

**Comment by ariesdevil** [comment] 2017-06-03 12:18
@mafredri same issue for me, I install pure use npm and my .zshrc config is following(use oh-my-zsh):
```shell
ZSH_THEME=refined
```
Use refined because I got this warning:

```shell
Oh My Zsh pure theme:

  The pure theme has been renamed as 'refined' as per the original author's
  request. Change your ZSH_THEME to 'refined' to avoid seeing this warning.
```

**Comment by mafredri** [comment] 2017-06-03 12:28
@ariesdevil that is not the Pure theme. You must disable zsh themes, see the readme section about zsh.

**Comment by ariesdevil** [comment] 2017-06-03 14:18
@mafredri I use antigen via ReadMe, my .zshrc is:

```shell
export ZSH=/Users/ariesdevil/.oh-my-zsh
source /usr/local/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle pip
antigen bundle command-not-found

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen apply

ZSH_THEME=''

plugins=(git osx colored-man-pages)

source $ZSH/oh-my-zsh.sh
```
not works for me...

**Comment by mafredri** [comment] 2017-06-03 14:28
@ariesdevil this is not related to this issue at all, if you have further questions, please open a new issue.

What you're seeing is not an issue with Pure, it's how you're using antigen / oh-my-zsh. Both `antigen use oh-my-zsh` and `source $ZSH/oh-my-zsh.sh` do the same thing, this means you should remove the `source` and you also need to perform your oh-my-zsh settings *before* `antigen use oh-my-zsh`.

**Comment by ariesdevil** [comment] 2017-06-03 14:34
@mafredri OK, thx~

**Comment by vaff** [comment] 2017-06-03 21:42
Sorry for the long response time, I'll return with more info soon

**Comment by vaff** [comment] 2017-06-13 09:05
I downloaded the files and sourced them:

```shell
# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
[ -f ${HOME}/.tmp/fzf-extras/key-binding.zsh ] && source ${HOME}/.tmp/fzf-extras/key-binding.zsh
[ -f ${HOME}/.tmp/fzf-extras/functions.sh ] && source ${HOME}/.tmp/fzf-extras/functions.sh
```

after I'm referencing pure

```shell

#
#
# zplug setup (https://github.com/zplug/zplug)
#
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug mafredri/zsh-async, from:github
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme
zplug "b4b4r07/emoji-cli"
zplug "changyuheng/fz", defer:1
zplug "rupa/z", use:z.sh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

#
#
# Pure integration
# https://github.com/sindresorhus/pure
#
autoload -U promptinit; promptinit
PURE_PROMPT_SYMBOL="🤜 "
prompt pure
```

**Comment by mafredri** [comment] 2017-06-13 16:49
@vaff, I've tried with your exact config, but I can't seem to reproduce the issue 🙁. I'm not able to trigger any errors.

**Comment by vaff** [comment] 2017-06-13 21:38
Hmn thats odd, must be something fishy with my setup then. You running it in hyperterm or ?

**Comment by mafredri** [comment] 2017-06-15 10:37
@vaff do you mean Hyper or some other terminal program? For me Hyper doesn't seem to understand the width of `🤜` resulting in some weirdness on the prompt line, but nothing like the errors you are experiencing.

Are you sure you're running the latest version of Pure? It doesn't seem like your config does `zplug update` at any point meaning you would be stuck on older versions until you manually update.

**Comment by vaff** [comment] 2017-06-15 11:04
The emoji works fine in my version of hyper. But mainly run iTerm. And there it is no issue.

I should be running the latest, I'll try to force a update and report back

**Comment by vaff** [comment] 2017-06-15 11:31
So it update / I updated Pure. The problem still persists.

**Comment by mafredri** [comment] 2017-06-15 18:06
Hmm, what version of `zsh` do you have @vaff? Although, if you're running `5.2` or newer, it shouldn't matter.

Could you also try out the following patch? It's seems far-fetched to me, but since the `fzf` functions deal with git, I'm not discounting the possibility:

```patch
diff --git a/pure.zsh b/pure.zsh
index b11ff53..69e5bbd 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -225,7 +225,7 @@ prompt_pure_async_vcs_info() {
 	zstyle ':vcs_info:git*' formats '%b' '%R'
 	zstyle ':vcs_info:git*' actionformats '%b|%a' '%R'
 
-	vcs_info
+	vcs_info || return
 
 	local -A info
 	info[top]=$vcs_info_msg_1_
@@ -352,6 +352,11 @@ prompt_pure_async_callback() {
 
 	case $job in
 		prompt_pure_async_vcs_info)
+			if (( code != 0 )); then
+				print "DEBUG: prompt_pure_async_vcs_info failed with exit code $code"
+				return
+			fi
+
 			local -A info
 			typeset -gA prompt_pure_vcs_info
 
```

**Comment by vaff** [comment] 2017-06-15 18:55
I'm running 5.2 of zsh

**Comment by vaff** [comment] 2017-06-16 08:22
So that actually prints the debug error.

```shell
DEBUG: prompt_pure_async_vcs_info failed with exit code 1
```

**Comment by mafredri** [comment] 2017-06-16 08:36
Great! Thanks for testing @vaff. This explains your issues as I had not previously considered that `vcs_info` could fail. My guess is that `vcs_info` printed some output to stdout which broke the assumption of only parsing the git info.

If you still feel up to test a bit, we could see what the actual output from `vcs_info` is, change the print a bit:

```
print "DEBUG: prompt_pure_async_vcs_info failed with exit code ${code}\nstdout: ${(q)output}\nstderr: ${(q)5}"
```

As I see it there are two options here, either we give up on error (as in my patch), or we retry until we are successful. The second option seems a bit dangerous though as we could end up in an infinite loop if it keeps failing constantly, so we would have to introduce a counter, etc. Maybe there could be a third option, a visual representation in the prompt that the check failed. I'll try to think about this some more and have a patch for this soon :-).

**Comment by vaff** [comment] 2017-06-16 11:21
sadly that didn't give us more information. the stdout and stderr are just blank.

**Comment by mafredri** [comment] 2017-06-16 11:55
Hmm, then I don't understand how the parsing failed earlier which gave you the error you first reported.

What does the stdout / stderr look like if you remove the `|| return` in `vcs_info || return` ?

Btw, can you give any more details on how this is triggered? I've not been able to trigger it a single time. I suppose you're inside a git repo, is there anything special about it? Are you using the keybindings e.g. Ctrl+G, Ctrl+H, etc?

**Comment by vaff** [comment] 2017-06-16 12:03
That is the idea yes. But I get the error when I source the files.

```shell
🤜  DEBUG: prompt_pure_async_vcs_info failed with exit code 1
stdout: ''
stderr: ''
```

**Comment by vaff** [comment] 2017-07-05 07:57
Could it be the first line in the functions.sh ?

```
is_in_git_repo
```

**Comment by vaff** [comment] 2017-07-05 08:21
I think I found out. It is something about the naming of the functions in both of the files. Renaming them works.

**Comment by mafredri** [comment] 2017-07-05 08:25
Hmm, what are you renaming? I don't see any conflicting names between Pure and the scripts 😕.

**Comment by vaff** [comment] 2017-07-05 09:53
I renamed the function gf, gb, gh etc. And i renamed the join-lines to join_lines. Suddenly it works.

**Comment by mafredri** [comment] 2017-07-05 10:12
None of those have anything to do with Pure, but I'm glad it works now 😄 !

Closing this as a one-off, not sure there's anything we can do about this in Pure since we don't understand the problem (and also wasn't reproducible for me).

**Closed by mafredri** 2017-07-05 10:12 UTC
