### ISSUE TITLE
OSX completion not working properly

### ISSUE THREAD

**Issue by elsesiy** [sindresorhus/pure#251] opened 2016-11-23 21:01 UTC
Hey there, 
first of all thanks for the great enhancement to zsh, I love it!

I do have a problem though:
Since I changed my `.zshrc` to use the pure theme, I'm not able to use basic os x completion tasks anymore, i.e.

`open -a Xcode sample.xcworkspace` doesn't work
I'm not able to type a `~` and so on..

I use the following plugins: `plugins=(git bundler osx zsh-syntax-highlighting)`

Thanks for the support and keep up the great work!

**Comment by mafredri** [comment] 2016-11-23 22:36
This does not sound related to pure at all. Try to trim down your .zshrc to find the culprit.

Also, what are the errors you're encountering? "Doesn't work" doesn't tell me much.

**Comment by elsesiy** [comment] 2016-11-24 19:29
Oh my bad, I meant to say that completion is not working for the `open` command. I can' type the `~` at all, the window is just flashing...

My .zshrc is very basic:

```
    autoload -U promptinit; promptinit    
    PURE_CMD_MAX_EXEC_TIME=10    
    prompt pure    
    export ZSH=/Users/elsesiy/.oh-my-zsh    
    ZSH_THEME="pure"    
    plugins=(git bundler osx zsh-syntax-highlighting)    
    source $ZSH/oh-my-zsh.sh
```

**Comment by mafredri** [comment] 2016-11-24 20:49
Pure doesn't have any effect on autocomplete or `~`, you should have a look at oh-my-zsh. For example, try disabling your plugins one-by-one, etc.

Also, you should follow the oh-my-zsh installation instructions, currently you are 1. loading pure the normal way, 2. overriding our pure with the oh-my-zsh integrated pure which is not the same thing.

Just to be sure, you should remove `prompt pure` from your zshrc and follow the installation instructions from before they were changed, see: https://github.com/sindresorhus/pure/commit/67f4c213d295ee50b61b68cbd584dd19efcee273 (e.g. you should use the 4-step version)

**Comment by elsesiy** [comment] 2016-11-24 21:17
@mafredri Thank you so much for getting back to me so quickly, I tried all the steps mentioned but it still doesn't work... I'll try my luck with the zsh repo maintainers if you've no further ideas but it seems that this is an issue throughout any shell on my machine at the moment. Running `/bin/sh` or `/bin/bash` typen `ALT + N` inputs a `:` for whatever reason..

**Comment by elsesiy** [comment] 2016-12-30 01:44
@mafredri I tried playing with my oh-my-zsh config as well but it didn't help. So I got rid of both and even with the plain shells (tried bash and zsh) it's the same weird behavior. 

I tried resetting everything by removing `.profile`, `.bash_profile`, deinstalling bash-completion, deleting `/Library/Preferences/com.apple.Terminal.plist` etc. and also switching the input source to any other language but nothing works.

Do you have any clue what to do in that case?

**Comment by mafredri** [comment] 2017-01-04 13:44
@elsesiy do you have a `.inputrc` file in your home folder? If so, that could be the cause of it, try removing / renaming it.

If that's not the issue, then sorry, I don't have an idea of what it could be :/.

**Comment by elsesiy** [comment] 2017-01-04 14:38
@mafredri I don't have that file. Anyway, the problem seems to be the Snazzy theme because as soon as I set the theme to default or any other it works. After changing it, everything seems to work fine and as I type this comment here, I just found this PR to fix the usage of Option as a metakey. https://github.com/sindresorhus/terminal-snazzy/pull/1

**Comment by mafredri** [comment] 2017-01-12 21:54
This seems to have been resolved over at the `terminal-snazzy` repository, closing here.

**Closed by mafredri** 2017-01-12 21:54 UTC
