### ISSUE TITLE
Prompt doesn't behave in tmux with Hyper

### ISSUE THREAD

**Issue by jc21** [sindresorhus/pure#301] opened 2017-02-26 12:17 UTC
### General information

- Pure version: 1.5.1
- ZSH version: 5.2 (x86_64-apple-darwin16.0)
- Terminal program & version: Hyper 1.2.1 (1.2.1.1527)
- Operating system: Darwin 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
- ZSH framework: none

I have:
- [ ] Tested with another terminal program and can reproduce the issue:
  - This is specific to Hyper it seems
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

This doesn't make the prompt unusable, just a little annoying in these circumstances.

When using vanilla tmux with this zsh pure prompt in Hyper, the first and second characters I type moves 1 space prior to where it should, then the following characters shows in the correct position. ie:

```shell
❯cl ear
```
instead of
```shell
❯ clear
```

- This does not happen when using iTerm.
- I have tried without my usual tmux config which still produces this result.
- I've tested zsh without pure prompt in Hyper and cannot reproduce this issue.

### Reproduction steps

1. use Hyper, install tmux, zsh
2. install pure prompt
3. run `tmux`
4. start typing a command

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment] 2017-02-26 17:01
I'm unable to reproduce using `Hyper 1.2.1.1528`, `zsh 5.2 (x86_64-apple-darwin16.0)` and `tmux 2.3` on macOS Sierra (`10.12.3 (16D32)`).

This leads me to believe this is one of:
1. A system configuration issue with Hyper, similar to https://github.com/sindresorhus/pure/issues/300#issuecomment-282532961.
2. A bug in Hyper and/or conflicting plugin
3. Font issue with Hyper

Without a way to reproduce this issue, there's nothing I can do, unfortunately 😔.

**Comment by jc21** [comment] 2017-02-26 23:03
Ok I'll keep digging..

**Comment by hugomd** [comment] 2017-03-01 23:37
Has anyone had any luck with this? I have exactly the same issue.

`tmux 2.3`
`Hyper 1.2.1.1528`

**Comment by dcalhoun** [comment] 2017-04-05 13:46
I experience this too, but I believe it is likely related to zeit/hyper#1156.

**Comment by mafredri** [comment] 2017-06-30 21:13
People are reporting improvements in https://github.com/zeit/hyper/issues/1156 after v1.3.3. Can anyone confirm if this is still an issue?

**Comment by dcalhoun** [comment] 2017-06-30 21:38
I do not believe I have experienced it recently. It may be resolved.

**Comment by mafredri** [comment] 2017-07-05 10:32
Thanks for reporting @dcalhoun! I'm closing this now as it seems to be fixed (judging by the lack of comments here).

**Closed by mafredri** 2017-07-05 10:32 UTC
