### ISSUE TITLE
VI mode eats previous prompt

### ISSUE THREAD

**Issue by johnpneumann** [sindresorhus/pure#485] opened 2019-07-12 02:36 UTC
### General information

- Pure version: 1.10.3
- ZSH version: 5.4.2+
- Terminal program & version: ssh
- Operating system: All
- ZSH framework: prezto and none

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
If you go quickly from command mode to insert mode, you'll consume the previous line. I tested this with prezto, as well as, just with the pure prompt (manual install). 

### Reproduction steps

1. Install the latest pure
2. Run `set -o vi`
3. Run `ls -la`
4. Hit `esc` and `i` in succession quickly.

### My `.zshrc`:

```shell
# .zshrc
autoload -U promptinit; promptinit
prompt pure
```

### Additional Information

@sindresorhus and @mafredri - I'm tagging y'all specifically because it's something worth noting. The prezto team has worked on a fix around the egregious line consumption, however, fast typers (and mechanical keyboard users) are probably going to notice this at some point. This doesn't appear to be a duplicate, however, I didn't go through closed issues. Moving on...

You can see the entire conversation in https://github.com/sorin-ionescu/prezto/issues/1641 which has been tons 'o fun. ;) [to be fair it's been interesting to dig into the source and reproduce on multiple os']

Specifically see this: https://github.com/sorin-ionescu/prezto/issues/1641#issuecomment-510068828 and https://github.com/sorin-ionescu/prezto/pull/1721

I'd be happy to discuss further, but I honestly haven't dug into the pure source code enough to determine how to fix it. It appears that the issue is triggered during the async operation. I can provide the logs I've gathered if it'd be helpful.

**Comment by kuba-gaj** [comment] 2019-07-16 11:28
same problem, had to temporary switch to another prompt :(

**Comment by scresante** [comment] 2022-06-05 04:56
I didn't expect to see this issue pop up again - I was having a similar problem when using [zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode/issues/124#issuecomment-1144138101 ) . 

I've since switched back to using zsh-vim-mode and I encountered this problem when trying out the pure prompt. 

Just thought I'd mention it: I've seen it before.

**Comment by mafredri** [comment] 2022-06-05 08:54
@scresante I can't reproduce, but I can take a look at it if you can provide a repro.

**Comment by mafredri** [comment] 2022-06-05 09:25
I can't reproduce this issue with zsh 5.9 on macOS, I'm closing this due to age (and there could be fixes to zsh that have fixed this). If it's still a problem, and reproducible with a minimal Pure setup (no plugins and up-to-date zsh), feel free to comment/reopen, if possible with more details on how to reproduce.

**Closed by mafredri** 2022-06-05 09:25 UTC

**Comment by neovimnovum** [comment] 2022-06-09 04:00
I can reproduce this issue on macOS with a fresh installation of zsh 5.9 from Homebrew. The issue goes away when zsh-vi-mode is commented out, and cannot be reproduced when it's only vanilla vi mode. The issue also goes away when pure is disabled. So my best guess is a plugin compatibility issue, just wanted to add a comment here because I've noticed it.

**Comment by nwaywood** [comment] 2022-09-07 07:53
I had this problem too, the following fixed it for me  https://github.com/jeffreytse/zsh-vi-mode/issues/124#issuecomment-1239033673
