### ISSUE TITLE
Installation issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by hyphaene** [sindresorhus/pure#342] opened 2017-08-25 11:14 UTC
### General information

- Pure version: 1.5.2
- ZSH version: 5.4.2
- Terminal program & version: terminator 0.97
- Operating system: Ubuntu 14.04
- ZSH framework: oh-my-zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue:hyper terminal
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
> pure-prompt@1.5.2 postinstall /usr/local/lib/node_modules/pure-prompt
> PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions

ln: impossible de créer le lien symbolique «/usr/local/share/zsh/site-functions/prompt_pure_setup»: Permission non accordée

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/dev/.config │
└───────────────────────────────────────────────────────┘

> pure-prompt@1.5.2 postinstall-link /usr/local/lib/node_modules/pure-prompt
> mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"

mkdir: impossible de créer le répertoire «/usr/local/lib/node_modules/pure-prompt/functions»: Permission non accordée
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.5.2 postinstall-link: `mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pure-prompt@1.5.2 postinstall-link script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/dev/.config │
└───────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2017-08-25T11_11_25_184Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pure-prompt@1.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2017-08-25T11_11_25_270Z-debug.log

### Reproduction steps
launch the npm install command

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment] 2017-08-25 13:23
This seems similar to #341. No idea why it's failing.

Can you post the full output of: `ls -lha /usr/local/lib/node_modules/pure-prompt` ?

**Comment by LitoMore** [comment] 2017-08-31 04:01
I have the same issue.

The full output of `ls -lha /usr/local/lib/node_modules/pure-prompt` is:

```
ls: cannot access '/usr/local/lib/node_modules/pure-prompt': No such file or directory
```

**Comment by mafredri** [comment] 2017-08-31 11:08
@LitoMore was your error identical to what @hyphaene had (e.g. same folders, etc)?

* Where is npm installing pure for you?
* How do we figure out the correct directory?

The current installation script relies on `$PWD` being the directory where pure was installed.

**Comment by LitoMore** [comment] 2017-08-31 12:11
Sorry, my mistake, I forgot my `node_modules` is in the `/usr/lib`. **NOT** `/usr/local/lib`.

The full output of `ls -lha /usr/lib/node_modules/pure-prompt` is:

```
ls: cannot access '/usr/lib/node_modules/pure-prompt': No such file or directory
```

---

> Where is npm installing pure for you?

```
/usr/lib/node_modules/pure-prompt
```

---

### My info:

- Pure version: 1.5.2
- Zsh version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
- Zsh framework: oh-my-zsh
- Terminal program & version: iTerm2 Build 3.1.beta.8
- Node version: 8.4.0
- NPM version: 5.3.0
- OS: Ubuntu 16.04
- User: root
- `echo $PWD`: `/root`

<div></div>

- [x] Tested with another terminal program and can reproduce the issue:hyper terminal
- [x] Followed the Integration instructions for my framework

**This is my output of** `npm i -g pure-prompt`**:**

```
> pure-prompt@1.5.2 postinstall /usr/lib/node_modules/pure-prompt
> PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions

glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> pure-prompt@1.5.2 postinstall-link /usr/lib/node_modules/pure-prompt
> mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"

mkdir: cannot create directory ‘/usr/lib/node_modules/pure-prompt/functions’: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.5.2 postinstall-link: `mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pure-prompt@1.5.2 postinstall-link script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! pure-prompt@1.5.2 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the pure-prompt@1.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-31T11_31_47_991Z-debug.log
```

**Comment by mafredri** [comment] 2017-08-31 12:18
@LitoMore are you installing as root (e.g. via sudo)? If so, that's probably the issue. Take a look at the issues I've linked to here: https://github.com/sindresorhus/pure/issues/341#issuecomment-326000184.

**Comment by LitoMore** [comment] 2017-08-31 12:21
@mafredri Yes, is root.

Thanks.

**Comment by chabib** [comment] 2017-10-12 08:19
Any update on this?

**Comment by kedwin** [comment] 2017-10-29 20:28
try this
npm install --global pure-prompt --allow-root --unsafe-perm=true

**Comment by mafredri** [comment] 2018-02-08 16:33
Closing due to age.

**Closed by mafredri** 2018-02-08 16:33 UTC
