### ISSUE TITLE
Prompt lines cut off when using completion

### ISSUE THREAD

**Issue by iroedius** [sindresorhus/pure#319] opened 2017-05-01 05:59 UTC
After 4cdd0cf4f48d0c2064700c4fc60083bc0b3f6693 every time tab completion is used, the path line, the line above it and the prompt symbol get cut off. For example: 
```

~
❯ ls testt<TAB>
```
Becomes:

```
  ls test
 -- no matches found --
```
The command goes **two** lines up. Reverting to c5876d3c4bc733ac6acdf3f96c17eaef7b242b62 solves the issue.

**Comment by mafredri** [comment] 2017-05-02 06:37
I'm unable to reproduce this, could you provide some more info, perhaps a minimal repro?

Also, what terminal are you using?

**Comment by iroedius** [comment] 2017-05-02 07:55
I use rxvt-unicode. Ok, I'm going to try to isolate the problem by disabling parts of my zsh configuration.

**Comment by iroedius** [comment] 2017-05-02 08:20
I got it. This is the cause:
```
expand-or-complete-with-indicator() {
  print -n '...'
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-indicator
bindkey '\C-I' expand-or-complete-with-indicator
```

The code is from [prezto](https://github.com/sorin-ionescu/prezto). I just checked and indeed it runs into the same issue.

**Comment by mafredri** [comment] 2017-05-03 16:12
Hmm, so does it work correctly for you now @iroedius? Assuming you made some modifications?

If not, would you have a chance to test another terminal? Wondering if it could be an rxvt-unicode + zsh issue.

I'm not able to reproduce in any terminal 😕.

**Comment by iroedius** [comment] 2017-05-05 07:58
Yes, removing the pasted code solves the issue.

I will try to test other terimnals soon.

**Comment by iroedius** [comment] 2017-05-07 08:02
I have been able to reproduce on any terminal i tried.

**Comment by mafredri** [comment] 2017-05-07 10:28
I stumbled upon this, seems like it could be relevant: https://github.com/sorin-ionescu/prezto/issues/1245.

Supposedly this might be fixed on the zsh master branch, you could try building/installing it and see if it helps. If you have a mac available, you can do it via Homebrew: `brew reinstall zsh --HEAD` (WARNING: This will uninstall zsh before building the new one, thus breaking zsh for the time of the build, switch to `/bin/zsh` or `bash` while building :)).

Furthermore, I've noticed noticed two other issues that may or may not be related:

* `iTerm` has refresh issues on first prompt (or after clearing screen `^L`), it keeps printing a new prompt below every refresh (Terminal and Hyper are unaffected)
* Calling `zle .reset-prompt` when completion is active and the cursor has moved away from the prompt-line is not handled correctly, everything except the highlighted word is erased (this seems like it would be a zsh issues)

**Comment by mikafouenski** [comment] 2017-05-17 07:55
I can confirm this issue on gnome-terminal 3.24.2 with zsh 5.3.1 and oh-my-zsh from git version.

**Comment by iroedius** [comment] 2017-08-08 16:10
The issue is no longer present when using zsh 5.4.

**Comment by mafredri** [comment] 2017-08-12 14:47
That's great news @iroedius, thanks for reporting in. Can you confirm the same @mikafouenski?

**Comment by mikafouenski** [comment] 2017-08-14 18:53
Everything is working as expected with [2181e9](https://github.com/sindresorhus/pure/commit/2181e9033eb665c21a76db456534a1ffe82a603e) and zsh 5.4.1 :+1: 
You can close this I think.

**Comment by mafredri** [comment] 2017-08-14 18:54
Thanks for confirming @mikafouenski!

**Closed by mafredri** 2017-08-14 18:54 UTC
