### ISSUE TITLE
Shell processes aren't getting killed on Windows

### ISSUE THREAD

**Issue by aspyatkin** [sindresorhus/pure#141] opened 2015-07-09 16:26 UTC
Hello, I ran into a problem while using `pure` on windows 8.1 machine. I use [Babun](https://github.com/babun/babun) shell (which is a slightly customized Cygwin with minty shell) with zsh 5.0.7.
![windows](https://cloud.githubusercontent.com/assets/4273812/8600634/e9ce923a-2677-11e5-8226-1f07ff6b0dce.png)
 I did the following:
1. start shell
2. start tmux
3. add three tabs in tmux
4. kill all tabs in tmux
5. observe an increased number of zsh processes
I can't reproduce this on machine with Mac OS X with iTerm2 (zsh also 5.0.7). Processes are killed in time.
<img width="794" alt="macos" src="https://cloud.githubusercontent.com/assets/4273812/8600691/51920cee-2678-11e5-8cf6-03efd654b18d.png">

Any thoughts on this?

**Comment by mafredri** [comment] 2015-07-09 16:37
Not in the slightest! I think for some reason zsh isn't receiving a cease-and-desist order.
You could try adding this to your zshrc after `prompt pure`

```zsh
function zshexit() {
    zpty -d prompt_pure
}
```

If that fixes it, it gives me some clues as to what is happening :).

**Comment by aspyatkin** [comment] 2015-07-09 17:49
@mafredri I am using `oh-my-zsh` integration, so I don't have `propmt pure` in my `zshrc`. I added lines you had suggested to `zshrc`, but seems that it didn't work.

**Comment by mafredri** [comment] 2015-07-09 18:30
Ok, in that case, did you add them last, so that oh-my-zsh is initialized before the `zshexit` function? Also, is this only reproducible when `pure` is active, not with other themes?

**Comment by aspyatkin** [comment] 2015-07-09 18:51
@mafredri Yes, I added these lines to the end of zshrc. Previously I used "standard" theme from the creator of oh-my-zsh (afair it is called robyrussel), there was no issues.

**Comment by mafredri** [comment] 2015-07-09 18:57
Sadness! Ok, next step, try commenting out this line [pure.zsh#L144](https://github.com/sindresorhus/pure/blob/1.1.1/pure.zsh#L144) and see if you can still reproduce.

**Comment by aspyatkin** [comment] 2015-07-10 03:43
@mafredri When I comment this line, I cannot reproduce the problem.

**Comment by forivall** [comment] 2015-07-10 07:27
Yeah, I use babun too when I'm on Windows, and I just use pure before all of the async stuff was added (5ade8aeb8). I'll help debug and fix this when I get back home.

**Comment by mafredri** [comment] 2015-07-10 10:28
Really appreciate it if you can help on this @forivall. I believe the problem lies somewhere with zsh not properly cleaning up after zpty, or perhaps zpty not cleaning up after itself. This might actually be solvable in `zsh-async`.

@aspyatkin so trying to further narrow this problem down. Could you try doing this and see if you can reproduce the problem?

1. Make sure to **undo** previous changes (comment) to line 144.
2. Before closing (any) tmux window (do this in all windows):
    1. `zpty -L # See that worker is running`
    2. `zpty -d prompt_pure # Delete worker`
    3. `zpty -L # See that worker is not running`
3. Close tmux window

Repeat steps 1 - 3 but replace 2 with:
* `zmodload -u zsh/zpty`

**Comment by aspyatkin** [comment] 2015-07-10 10:43
@mafredri I didn't manage to reproduce all the steps. Either `zpty -d prompt_pure` or `zmodload -u zsh/zpty` freezes my shell, so I have to kill zsh processes with Windows task manager.

**Comment by mafredri** [comment] 2015-07-10 15:39
@aspyatkin then it seems like there is some sort of weirdness in the zsh build, or a result of running zsh on windows. I've got one more idea how to circumvent your issue.

Apply this patch to async.zsh
```patch
diff --git a/async.zsh b/async.zsh
index d62cb17..9096caf 100644
--- a/async.zsh
+++ b/async.zsh
@@ -58,6 +58,8 @@ _async_worker() {
 
                # Check for non-job commands sent to worker
                case "$job" in
+               _exit)
+                       return 0
                _killjobs)
                        kill -KILL ${${(v)jobstates##*:*:}%\=*} &>/dev/null
                        continue
```

There actually two variants you can try for this patch, the second is: replace `return 0` with `exit 0`

And to your `.zshrc`:

```zsh
function zshexit() {
    zpty -w prompt_pure _exit
}
```

**Comment by aspyatkin** [comment] 2015-07-10 16:06
@mafredri I open shell and see two zsh processes in Windows Task manager. Then press Ctrl+D to exit.
*Without the patch:* there are two processes remaining, shell window freezes.
*With the patch:* one process is getting killed, the other remains, shell window freezes.
Hope this helps.

**Comment by mafredri** [comment] 2015-07-10 16:12
Ok, thinking maybe the coproc is left running somehow, try this patch maybe?

```patch
diff --git a/async.zsh b/async.zsh
index d62cb17..3448956 100644
--- a/async.zsh
+++ b/async.zsh
@@ -58,6 +58,9 @@ _async_worker() {
 
                # Check for non-job commands sent to worker
                case "$job" in
+               _exit)
+                       coproc exit
+                       exit 0
                _killjobs)
                        kill -KILL ${${(v)jobstates##*:*:}%\=*} &>/dev/null
                        continue
```

**Comment by aspyatkin** [comment] 2015-07-10 16:37
@mafredri Same thing, one process is getting killed, the other remains.
I think this is somehow a problem with zsh running on Windows. Maybe it will reproduce on Windows 10 (I haven't tested), and you can install a preview version (I suppose it's free) to reproduce the bug. Or I can build a Vagrant box with Windows 10 and upload it on Vagrant cloud, but this will require 8-10 Gb of network payload (windows boxes are really huge).

**Comment by mafredri** [comment] 2015-07-10 19:17
I tried downloading babun on my modern.IE VM (Win 8.1). This is definitely a problem with zsh on Windows (or potentially just babun). Without any modifications I'm unable to perform basic zpty operations without hanging the shell. I suggest opening a bug report with babun, seeing as this is not a problem with pure.

**Comment by mafredri** [comment] 2015-07-10 19:24
Closing for now since I feel there's nothing more I can do here.

**Closed by mafredri** 2015-07-10 19:24 UTC

**Comment by aspyatkin** [comment] 2015-07-11 05:46
OK, thank you very much for spending your time for investigation.

**Comment by 2c2c** [comment] 2016-01-01 04:49
i came across this googling around-- this issue goes deeper than what this seems to touch on. running node servers cant be killed with ctrl-c for example in babun. some universal issue with killing processes
