### ISSUE TITLE
Prompt eats single line output

### ISSUE THREAD

**Issue by radiosilence** [sindresorhus/pure#410] opened 2018-06-01 12:18 UTC
### General information

- Pure version: 1.6.0
- ZSH version: 5.5.1
- Terminal program & version: alacritty@master
- Operating system: macOS Sierra 10.13.4
- ZSH framework: prezto

I have:
- [x] Tested with another terminal program and can reproduce the issue:
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
If I do any command with output shorter than the width of my terminal (e.g. a 20 character response for an 80 character terminal) the output doesn't appear

### Reproduction steps

1. `print -n lol`
2. NO LOL

### My `.zshrc`:

https://github.com/radiosilence/dotfiles/blob/master/.zshrc

**Comment by mafredri** [comment] 2018-06-01 23:48
Hey, this should be fixed in master (https://github.com/sindresorhus/pure/commit/9fa64040b1137dc4bd94dc3a41bef0ef69f93d79), does updating fix your issue?

**Comment by lyndsysimon** [comment] 2018-08-02 16:37
I cannot reproduce this.

Pure version: master (commit 5976e54a7b02e4be34649fa43b7f0e53b139355f)
ZSH version: 5.5.1 (x86_64-apple-darwin17.5.0)
Terminal program & version: Hyper@2.0.0; iTerm2@3.1.7
Operating system: macOS Sierra 10.13.6

**Comment by mafredri** [comment] 2018-08-20 08:45
Thanks for your input @lyndsysimon, v1.8.0 is out now so this issue is (probably) fixed.

**Closed by mafredri** 2018-08-20 08:45 UTC
