### ISSUE TITLE
[Feature Request] Show node version for JS-specific folders

### ISSUE THREAD

**Issue by d3lm** [sindresorhus/pure#528] opened 2020-02-10 08:34 UTC
It would be great if we could also show the node version only for JS-specific folders that maybe contain a `package.json` or `node_modules`. When switching the working tree the information in the prompt should be updated accordingly. Here's an example of what I am imagining:

![image](https://user-images.githubusercontent.com/12571019/74133214-5e9c0300-4be8-11ea-8754-51cdb5712c34.png)

I have implemented this locally and would be willing to send my changes as a PR. However, I am not sure if it's the proper way of implementing it because I personally don't have that much experience with bash programming. But I'd love to get this in and get your feedback on my implementation. I was mostly inspired by how the git stuff is done asynchronously.

**Comment by sindresorhus** [comment] 2020-02-13 08:16
Yeah, would be useful. We're looking into how to be able to do this in a more modular way to make it easier for people to enable/disable certain part, like this and even make their own: https://github.com/sindresorhus/pure/issues/460

**Comment by sindresorhus** [comment] 2020-02-13 08:17
Duplicate of #503

**Comment by sindresorhus** [comment] 2020-02-13 08:17
^ You should comment there instead.

**Closed by sindresorhus** 2020-02-13 08:17 UTC
