### ISSUE TITLE
prompt at the bottom when quits vim

### ISSUE THREAD

**Issue by r8b7xy** [sindresorhus/pure#151] opened 2015-07-27 08:49 UTC
Prompt is at the bottom when I quit from vim.
![prompt](http://i.imgur.com/XWft4HA.png)
I don't know whether or not this is wrong but I simply added this to zshrc:
```
source ~/.zsh/plugins/async.zsh
source ~/.zsh/plugins/pure.zsh
```
EDIT:
Problem persist even with antigen:
```
#plugins
source ~/.zsh/antigen/antigen.zsh

antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
```
similar problem [superuser.com](http://superuser.com/questions/820838/vim-leaving-empty-display-on-exit)

Problem isn't present on another desktop with same dotfiles, weird.

**Comment by mafredri** [comment] 2015-07-27 09:46
It doesn't look like it's anything specific that `pure` is doing. Can't reproduce. Might be helpful if you posted your `.zshrc`, and if the problem isn't there it might be your `.vimrc`.

**Comment by r8b7xy** [comment] 2015-07-27 09:48
It seems like this line in vimrc is the issue:
```
let g:base16_shell_path="~/.config/base16-shell"
```
Vim needs this scripts for switching base16 colorschemes.
https://github.com/chriskempson/base16-shell/

**Comment by mafredri** [comment] 2015-07-27 10:08
Alright, feel free to post a solution if you find one. Closing this since it's unrelated to `pure`.

**Closed by mafredri** 2015-07-27 10:08 UTC
