### ISSUE TITLE
Extra spacing after prompt with tmux over ssh

### ISSUE THREAD

**Issue by funnell** [sindresorhus/pure#263] opened 2016-12-16 22:14 UTC
### General information

- Pure version: 1.4.1
- ZSH version: zsh 5.1.1
- Terminal program & version: iTerm 3.0.0, Hyper 1.0.0
- Operating system: OS X 10.10.5
- ZSH framework: antibody

I have:
- [X] Tested with another terminal program and can reproduce the issue
- [X] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

I ssh to a remote server, then start a tmux session. There is extra space after the prompt like so
```
~
❯   ls
```

whereas I would expect
```
~
❯ ls
```

Performing certain tmux actions like splitting the screen seems to remove the extra space from already typed commands (but not new ones). Using Pure remotely without tmux works fine, using tmux locally works fine. Switching to a different prompt character '$' works fine without the extra space.

### Reproduction steps

1. ssh to remote server
2. start a tmux session

### My `.zshrc`:

```shell
source <(antibody init)
antibody bundle mafredri/zsh-async
antibody bundle sindresorhus/pure
```

**Comment by mafredri** [comment] 2016-12-17 10:50
Thanks for the report! I think this is a problem with tmux (or a combination of ncurses/tmux/zsh) on the remote machine. My guess is that the character width is not calculated properly for unicode characters.

Can you reproduce if you replace your `.zshrc` with just:

```shell
PROMPT='%F{magenta}❯%f '
```

Further, these could be helpful (from the server):

* Operating system & version
* ZSH version (unless it's 5.1.1 as you wrote)
* tmux version
* tmux configuration

**Comment by funnell** [comment] 2017-01-06 21:26
Thanks for the response!

I can reproduce the issue by replacing my .zshrc as you suggested.

On the server:
* OS: CentOS release 6.5
* ZSH: 5.1.1 (x86_64-pc-linux-gnu)
* tmux: 2.1
* tmux conf: https://gist.github.com/funnell/c0df74d4e5ec337f9ce84f238389af4a

**Comment by mafredri** [comment] 2017-01-12 21:52
@funnell since you're using tmux `2.1` you must probably enable utf8, `2.2` has automatic detection, see tmux [CHANGES](https://github.com/tmux/tmux/blob/master/CHANGES).

**Comment by funnell** [comment] 2017-01-16 19:46
Thanks for the suggestion @mafredri. I've added
```
set -g utf8
set-window-option -g utf8 on
```
to the top of my .tmux.conf with no luck.
This is a very minor issue and I'm happy switching to a different character, so feel free to ignore this issue :)

**Comment by mafredri** [comment] 2017-01-16 19:50
Sorry to hear it didn't help :(. Anyway, if you ever do find a solution, feel free to post it here! I'll close this for now as I have no leads on how to investigate this further (without trying to replicate your OS setup).

**Closed by mafredri** 2017-01-16 19:50 UTC
