### ISSUE TITLE
Variable for dirty repo indicator

### ISSUE THREAD

**Issue by vaff** [sindresorhus/pure#287] opened 2017-02-08 11:18 UTC
The support for a variable for the dirty repo indicator would be great. I'd like to customize it to make it more visible. Maybe with an emoji, like I've done with the PURE_PROMPT_SYMBOL

![screen shot 2017-02-08 at 12 14 18](https://cloud.githubusercontent.com/assets/351447/22735009/261bc7f0-edf8-11e6-8b34-ab6bd4c6f342.png)

**Comment by mafredri** [comment] 2017-02-12 12:30
Sorry, it would be nice to cater to everyones use-cases but we're not too keen on adding configuration options, duplicate of #167.

**Closed by mafredri** 2017-02-12 12:30 UTC

**Comment by vaff** [comment] 2017-02-12 16:41
Ah my fault. I didn't do a proper search for duplicates.
