### ISSUE TITLE
git branch name gets out of sync

### ISSUE THREAD

**Issue by jlebar** [sindresorhus/pure#536] opened 2020-03-04 17:37 UTC
#### System report (output of `prompt_pure_system_report`):

- Zsh: zsh 5.8 (x86_64-apple-darwin19.3.0)
- Operating system: Mac OS X 10.15.3 (19D76)
- Terminal program: Apple_Terminal (433)
- Git: git version 2.25.0
- Pure state:
	- username: `''`
	- prompt: `❯`
	- version: `1.10.3`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Prompt: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f %F{242}${prompt_pure_vcs_info[branch]}%F{218}${prompt_pure_git_dirty}%f %F{$prompt_pure_colors[git:arrow]}${prompt_pure_git_arrows}%f
%{
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Detected frameworks: Oh My Zsh
	- Oh My Zsh:
		- Plugins: git, history-substring-search

#### I have:

- [ ] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

When using my terminal normally, I find that the git branch name gets out of sync with git's actual branch.  For example right now

```
~/repo jlebar/l10n ⇣⇡
❯ git branch | cat
  jlebar/l10n
* master
```

Once this happens it seems "stuck" -- I can't seem to get it to refresh again by e.g. checking out other branches.

### Reproduction steps

I haven't been able to reproduce this on demand, but it happens at least once a day.

### My `.zshrc`:

I don't have a minimal zshrc because it takes a while of using my computer normally to reproduce the issue.  Here's my whole zshrc; hopefully nothing too surprising in here.

```
# Path to your oh-my-zsh installation.
export ZSH="/Users/jlebar/.oh-my-zsh"
ZSH_THEME=""  # using pure, below
plugins=(git history-substring-search)
source $ZSH/oh-my-zsh.sh
autoload -U promptinit; promptinit
prompt pure

export CONFDIR="$HOME/code/conf"
path+=($CONFDIR/bin)
export PATH

# Add GNU utilities to path.  I know you're not supposed to do this,
# but...yeah.  I have the `nognu` script that lets me run code without this.
# From https://apple.stackexchange.com/questions/103228/homebrew-easy-way-to-add-gnubin-to-path-for-multiple-packages
if type brew &>/dev/null; then
  HOMEBREW_PREFIX=$(brew --prefix)
  # gnubin; gnuman
  for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnubin; do export PATH=$d:$PATH; done
  # I actually like that man grep gives the BSD grep man page
  for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnuman; do export MANPATH=$d:$MANPATH; done
fi

alias ls='ls --color=auto'
export EDITOR="vim"

###### vi-mode ######
# The "pure" prompt says not to enable oh-my-zsh vi-mode plugin for whatever reason.

bindkey -v

# allow v to edit the command line (standard behaviour)
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

# allow ctrl-p, ctrl-n for navigate history (standard behaviour)
bindkey '^P' up-history
bindkey '^N' down-history

# allow ctrl-h, ctrl-w, ctrl-? for char and word deletion (standard behaviour)
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word

# allow ctrl-r and ctrl-s to search the history
bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward

###### vi-mode ######
```

**Comment by sindresorhus** [comment] 2020-03-06 18:07
Duplicate of https://github.com/sindresorhus/pure/issues/455

**Closed by sindresorhus** 2020-03-06 18:07 UTC
