### ISSUE TITLE
Command is added twice to promt after hitting tab

### ISSUE THREAD

**Issue by megawubs** [sindresorhus/pure#248] opened 2016-11-10 20:25 UTC
When I do the following:

```zsh
❯ cd ~/P
```
and hit `tab` the result I get is this:

```zsh
❯ cdcd ~/P
Pictures/  Projects@  Public/ 
```
It's also not possible to remove the first `cd` when using the backspace to clear the command.

it happens with every command that has multiple options when using tab completion.

**Comment by mafredri** [comment] 2016-11-10 20:34
What's your zsh version and can you reproduce this with a minimal zshrc? If so, could you provide the zshrc that reproduces the issue?

**Comment by megawubs** [comment] 2016-11-10 21:02
```zsh
❯ zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

```zsh
❯ cacat ~/.zshrc 
source /Users/me/Projects/Github/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

# Tell antigen that you're done.
antigen apply

export PATH="./bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:$HOME/bin"

PATH="$PATH:$HOME/.composer/vendor/bin"
export XDEBUG_CONFIG="idekey=PHPSTORM"
export PHP_IDE_CONFIG="serverName=local"

source ~/.aliases
```

`~/.aliases` is just a long list of alias commands

**Comment by mafredri** [comment] 2016-11-10 21:04
Thanks, did you try without oh-my-zsh?

**Comment by megawubs** [comment] 2016-11-10 21:11
no, will try that now

**Comment by megawubs** [comment] 2016-11-10 21:22
When using bash or sh, it doesn't happen

**Comment by mafredri** [comment] 2016-11-10 21:44
Does it also happen without pure? Bash and sh won't be relevant to this issue (there's no pure for them) so you don't need to compare those.

Honestly I'm not sure what it could be, it seems like it's something unique to your environment. I was betting on some oh-my-zsh configuration (which is why I wondered if you tried without it). There's also the fact that oh-my-zsh has a theme named pure which can conflict if you try to activate it from oh-my-zsh.

I can't reproduce this issue (then again I'm not using oh-my-zsh).

I would recommend you upgrade your zsh though (e.g. through Homebrew), just in case (also, 5.2 has a lot of improvements over 5.0.8).

**Comment by megawubs** [comment] 2016-11-10 22:12
As soon as i turn pure of in my `~/.zshrc` the problem is gone. I've updated both `oh-my-zsh` and `zsh`

Could it be `antigen`?

**Comment by megawubs** [comment] 2016-11-16 07:40
The issue gets worse as soon as I start a tmux session, tmux becomes unusable with pure :(

**Comment by mafredri** [comment] 2016-11-16 08:27
I've tried your exact setup, `antigen` with your `.zshrc` and cannot reproduce this issue.

So just to confirm, you're running the latest versions of `pure` and `zsh-async`? And your `zsh --version` is now `5.2`?

If so, the only thing remaining as an unknown is your terminal program (e.g. is it Terminal, iTerm?) and `~/.aliases` file.

**Comment by megawubs** [comment] 2016-11-16 18:01
Yes, `pure` and zsh-async` are both at the latest version (commit). In fact I just forked `pure` and added my fork as a remote to the installed version to do some debugging of my own. It turns out that Hyper (the missing pice of your puzzle) doens't like the `❯ ` character. In my current `pure.zsh` file, all code is commented out, except the last line setting the `PROMT` variable. See the screenshot. When I change the character, the behavior is gone. (tmux is still a mess, but I think it's not related to pure)

![image](https://cloud.githubusercontent.com/assets/2302867/20359090/9ed1a482-ac2e-11e6-9899-627a5a5b3693.png)

seems to be a Hyper related issue, as the it works fine on other both  iTerm als Terminal

**Comment by mafredri** [comment] 2016-11-16 18:08
Glad you found the issue. You could try changing the font in Hyper and see if that helps. I have tested Hyper myself and I do not experience this problem (tested on 0.8.1 and 0.8.3). Even with a clean hyper configuration I cannot reproduce.

Either way, closing this since it doesn't seem to be a `pure` issue. But feel free to post a fix, if you find one, so it can help others with a similar issue.

**Closed by mafredri** 2016-11-16 18:08 UTC

**Comment by henrikdahl** [comment] 2017-01-12 10:21
I'm also having this issue with everything updated. No custom settings or any plugins on Hyper. No custom font.

It's pretty annoying I can't seem to find why it does it. It doesn't happen in Terminal with same setup ✌️

**Comment by mafredri** [comment] 2017-01-12 21:46
@henrikdahl does it happen if you set `PROMPT='> '`? Not sure there's anything we can do here, seems like a hyper issue. You could also try changing fonts.

**Comment by henrikdahl** [comment] 2017-01-12 22:01
@mafredri doesn't seem to be related to the font, tried 4 different fonts and the default one.

It appears to be directly related to the prompt symbol. Tried changing it to for example `#`and that fixes it. Tried a couple of similar unicode characters and they all had the same issue.

I think the one you guys picked is perfect however so I'd love to see it work ✌️

**Comment by henrikdahl** [comment] 2017-01-12 22:02
Works fine with `>` as well.

<img width="496" alt="skarmavbild 2017-01-12 kl 23 02 30" src="https://cloud.githubusercontent.com/assets/1430576/21910181/399acf7a-d91b-11e6-9667-b24277fd2918.png">

**Comment by mafredri** [comment] 2017-01-12 22:06
How about `PROMPT='❯ '`? Pure symbol, but with no colors. What version of macOS do you have? And what does your `.zshrc` look like? Do you use a framework, e.g. oh-my-zsh, etc?

**Comment by henrikdahl** [comment] 2017-01-12 22:09
Still issue with just `PROMPT='❯ '`sadly. 

macOS 10.12.2

```
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

source $(brew --prefix)/share/antigen/antigen.zsh

antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen apply
```

**Comment by mafredri** [comment] 2017-01-12 22:12
Can't reproduce, sorry :-(.

Are you using Hyper 1.1.0?

**Comment by henrikdahl** [comment] 2017-01-12 22:14
Yeah. Np, I know how hard it is to debug from issues ✌️

If you get any ideas please let me know

**Comment by mafredri** [comment] 2017-01-12 22:17
One last though, have you tried closing hyper and wiping `.hyper.js` and `.hyper_plugins`, starting from scratch?

**Comment by henrikdahl** [comment] 2017-01-12 22:19
I'm fairly certain its a part of my setup. I've purchased the 2016 rMBP and cycled through 3 with Hyper and Pure, fresh install each time and they all had the same issue. Additionally my friend who I help setup his Hyper + Pure also has the same issue.

It might just be a Hyper bug? It's still odd that you can't reproduce it.

**Comment by mafredri** [comment] 2017-01-12 22:27
Hmm, very weird indeed. Have you tried updating zsh through homebrew? You should have 5.2 on the system, but 5.3.1 is available.

**Comment by henrikdahl** [comment] 2017-01-12 22:29
<img width="263" alt="skarmavbild 2017-01-12 kl 23 28 37" src="https://cloud.githubusercontent.com/assets/1430576/21911013/de6973c8-d91e-11e6-881c-9d763fa55b7d.png">

Which version are you running? I'll update ✌️

**Comment by mafredri** [comment] 2017-01-12 22:37
Well I'm running 5.3.1-dev-0 (HEAD-4fb4ce1) but it's pretty close to 5.3.1.

**Comment by henrikdahl** [comment] 2017-01-12 22:47
Still same issue 😓

**Comment by 0916174** [comment] 2018-04-20 23:40
Got the same issue.
_Pre-tab:_
<img width="213" alt="image" src="https://user-images.githubusercontent.com/14292245/39077817-d634a92c-4504-11e8-8f2d-58c90c60667a.png">

_Post-tab:_
<img width="484" alt="image" src="https://user-images.githubusercontent.com/14292245/39077828-e03309c8-4504-11e8-8677-abf3ec43e057.png">

Using the [Spaceship](https://github.com/denysdovhan/spaceship-prompt) theme in Hyper using oh-my-zsh.

**Comment by mafredri** [comment] 2018-04-21 08:46
@0916174 this is not the issue tracker for the spaceship theme, you should report your issue there or at oh-my-zsh.

**Comment by 0916174** [comment] 2018-04-21 09:32
Oh, sorry about that. It was quite late, so I wasn’t paying attention properly.

**Comment by amitz** [comment] 2020-04-01 07:11
Experiencing the same issue using macOS Catalina 10.15.4. As mentioned before, changing the `LC_CTYPE` to UTF-8 or just changing the Prompt Symbol to anything else, seems to work. So I'm assuming it's something around this specific character.

**Comment by ganeshhindinamani** [comment] 2021-09-01 13:48
I also had the same zsh issue on my Arch Linux, I forgot to create **/etc/locale.conf** file at the time of installation.
after creating the locale.conf file the issue resolved.

The content inside **/etc/locale.conf** file is:
LANG=en_US.UTF-8
