### ISSUE TITLE
prompt_pure_async_callback:2: no matches found: output=*

### ISSUE THREAD

**Issue by samimb** [sindresorhus/pure#169] opened 2015-10-22 08:36 UTC
Keep getting "prompt_pure_async_callback:2: no matches found: output=*" after including pure and async in my own zsh config.

**Comment by mafredri** [comment] 2015-10-22 10:06
Looks like some globbing problem. Output of: `zsh --version && setopt` would be helpful.

**Comment by samimb** [comment] 2015-10-22 10:24
zsh 5.0.8 (x86_64-apple-darwin15.0)
autopushd
nobeep
braceccl
cdablevars
noclobber
completealiases
completeinword
correct
cshjunkiehistory
extendedglob
extendedhistory
globcomplete
globsubst
histallowclobber
histignoredups
histignorespace
histverify
nohup
incappendhistory
interactive
interactivecomments
nolistambiguous
nolistbeep
login
longlistjobs
magicequalsubst
monitor
numericglobsort
pathdirs
posixbuiltins
nopromptcr
promptsubst
pushdignoredups
pushdsilent
pushdtohome
rcexpandparam
shinstdin
shoptionletters
zle

**Comment by mafredri** [comment] 2015-10-22 11:06
Thanks, I'm unable to reproduce, however. Would you mind sharing your zsh configuration?

**Comment by samimb** [comment] 2015-10-22 11:08
Anywhere I can send it to you?

**Comment by mafredri** [comment] 2015-10-22 11:10
Any method you like. Share it on your dropbox, google drive, put it in a gist, my emails on my profile, etc. :)

**Comment by mafredri** [comment] 2015-10-22 11:23
Tack för filterna ;).

So I can't find anything obvious in your configuration. What version of `pure` and `async` do you have? And would you mind trying it out with a "clean" `.zshrc` and following the manual installation method for example?

`.zshrc` should look something like this:
```zsh
fpath=( "$HOME/.zfunctions" $fpath )
autoload -U promptinit && promptinit
prompt pure
```

**Comment by samimb** [comment] 2015-10-22 11:27
Inga problem :).

There is definitely something in the conf.
Tried it with a "blank" one, works like a charm. Need to find what it is.

**Comment by mafredri** [comment] 2015-10-22 11:29
If you find it, do tell, I would like to be able to support all sorts of zsh configurations, but it's hard to know what options mess with what before actually encountering them :D

**Comment by samimb** [comment] 2015-10-22 11:30
setopt                       \
     NO_all_export           \
        always_last_prompt   \
     NO_always_to_end        \
        append_history       \
     NO_auto_cd              \
        auto_list            \
        auto_menu            \
     NO_auto_name_dirs       \
        auto_param_keys      \
        auto_param_slash     \
        auto_pushd           \
        auto_remove_slash    \
     NO_auto_resume          \
        bad_pattern          \
        bang_hist            \
     NO_beep                 \
        brace_ccl            \
        correct_all          \
     NO_bsd_echo             \
        cdable_vars          \
     NO_chase_links          \
     NO_clobber              \
        complete_aliases     \
        complete_in_word     \
     correct                 \
     NO_correct_all          \
        csh_junkie_history   \
     NO_csh_junkie_loops     \
     NO_csh_junkie_quotes    \
     NO_csh_null_glob        \
        equals               \
        extended_glob        \
        extended_history     \
        function_argzero     \
        glob                 \
     NO_glob_assign          \
        glob_complete        \
     NO_glob_dots            \
        glob_subst           \
        hash_cmds            \
        hash_dirs            \
        hash_list_all        \
        hist_allow_clobber   \
        hist_beep            \
        hist_ignore_dups     \
        hist_ignore_space    \
     NO_hist_no_store        \
        hist_verify          \
     NO_hup                  \
     NO_ignore_braces        \
     NO_ignore_eof           \
        interactive_comments \
	inc_append_history   \
     NO_list_ambiguous       \
     NO_list_beep            \
        list_types           \
        long_list_jobs       \
        magic_equal_subst    \
     NO_mail_warning         \
     NO_mark_dirs            \
     NO_menu_complete        \
        multios              \
        nomatch              \
        notify               \
     NO_null_glob            \
        numeric_glob_sort    \
     NO_overstrike           \
        path_dirs            \
        posix_builtins       \
     NO_print_exit_value     \
     NO_prompt_cr            \
        prompt_subst         \
        pushd_ignore_dups    \
     NO_pushd_minus          \
        pushd_silent         \
        pushd_to_home        \
        rc_expand_param      \
     NO_rc_quotes            \
     NO_rm_star_silent       \
     NO_sh_file_expansion    \
        sh_option_letters    \
        short_loops          \
     NO_sh_word_split        \
     NO_single_line_zle      \
     NO_sun_keyboard_hack    \
        unset                \
     NO_verbose              \
        zle

Something in here.

**Comment by mafredri** [comment] 2015-10-22 11:32
Ok, I can take a look later. (I don't think that was part of the config you sent me though).

**Comment by samimb** [comment] 2015-10-22 11:32
Oh, oops. I forgot to send the zshrc haha.

**Comment by samimb** [comment] 2015-10-22 11:34
setopt extended_history

**Comment by samimb** [comment] 2015-10-22 11:39
setopt glob_subst

**Comment by mafredri** [comment] 2015-10-22 11:47
I suspected that one, but could not reproduce.

Try this patch to async:

```patch
diff --git a/async.zsh b/async.zsh
index 8299bf0..1be8930 100644
--- a/async.zsh
+++ b/async.zsh
@@ -10,6 +10,7 @@

 # Wrapper for jobs executed by the async worker, gives output in parseable format with execution time
 _async_job() {
+       setopt localopts noglobsubst
        # Store start time as double precision (+E disables scientific notation)
        float -F duration=$EPOCHREALTIME
```

**Comment by samimb** [comment] 2015-10-22 11:53
still breaks, just cause I'm loading my opts after prompt.

**Comment by mafredri** [comment] 2015-10-22 12:13
Ok, I'm closing this now since we found the culprit, and it looks like I'm not going to be able to reproduce this without your .zshrc. Also, `glob_subst` seems pretty evil, breaks `z` as well (and erased my entrie `.z` dir database :cry:).

One should always be vary about enabling a bunch of zsh setopts unless they are needed for something specific :)

**Closed by mafredri** 2015-10-22 12:14 UTC
