### ISSUE TITLE
xcwd stops working when using pure prompt

### ISSUE THREAD

**Issue by fdietze** [sindresorhus/pure#207] opened 2016-04-17 11:30 UTC
When activating pure prompt, [xcwd](https://github.com/schischi/xcwd) stops working.

To reproduce, in one terminal start:
```sh
watch xcwd
```

Then open another terminal and change directories. When pure is deactivated, the path in the first terminal updates accordingly. However with pure prompt it doesn't.

Interestingly: When running ```exec zsh``` the directory updates once.

**Comment by mafredri** [comment] 2016-04-17 17:15
I don't have any way to try and reproduce at the moment, but you could try executing `zpty -d prompt_pure` and see if that fixes the problem. It will break some of the `pure` git functionality, and show errors, but it would indicate that the zpty is somehow interfering.

**Comment by cornerman** [comment] 2016-04-18 14:05
> try executing `zpty -d prompt_pure`

I have the same problem and, indeed, this fixes it.

**Comment by mafredri** [comment] 2016-04-18 14:16
Then I don't think there's a whole lot we can do, as far as I can tell, the zsh process does report the correct cwd according to `lsof -d cwd`. The problem is, as I figure, that there's a second zsh process running in that same instance (zpty) which has a different cwd (essentially `$HOME` since that's likely where zpty was started).

xcwd probably assumes that the most recent PID is the one we should check cwd from, in this instance that PID would be zpty :/.

**Comment by fdietze** [comment] 2016-04-19 15:01
Ok. Thanks for pointing me in the right direction. I will investigate further...

**Comment by mafredri** [comment] 2016-04-22 15:48
Alright, I hope you can find a solution! I'm closing this for now as I don't see there's anything we can do on our side. If you do find out something that we can help with, however, feel free to re-open or create a new issue :).

**Closed by mafredri** 2016-04-22 15:48 UTC
