### ISSUE TITLE
Prompt eats lines with right aligned segment

### ISSUE THREAD

**Issue by Piepow** [sindresorhus/pure#375] opened 2017-12-19 21:42 UTC
### General information

- Pure version: 1.6.0
- ZSH version: 5.2
- Terminal program & version: termite v13
- Operating system: Ubuntu 17.10
- ZSH framework: oh-my-zsh

### Problem description
I am in the process of modifying pure, and one of the things I tried to do is add a timestamp to the right of the preprompt. However, I ran into an issue:

![peek 2017-12-19 16-19](https://user-images.githubusercontent.com/20409621/34179660-d15fc7f0-e4d9-11e7-97d9-294306ad2dc1.gif)

It seems like refreshing the prompt async (tested by entering a directory with a git repo) causes lines to be lost. I'm pretty new to zsh, so I'm not quite sure what exactly is causing this.
### Reproduction steps

1. Use my fork of pure: https://github.com/Piepow/pure/tree/stripe

![screenshot from 2017-12-19 16-38-04](https://user-images.githubusercontent.com/20409621/34179997-0ab301ba-e4db-11e7-8f89-23476eddb529.png)

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment] 2018-01-06 15:14
@Piepow this happens because ZLE thinks `$prompt_newline` takes up space in the prompt. Thus it's calculation is off by 1 and it thinks the prompt starts on the next line. As a result it moves up one line when it should not. This is easily solvable by telling ZLE that the newline takes no space:

```zsh
'%{'$prompt_newline'%}'
```

The relevant position is this here: [pure.zsh#L15-16](https://github.com/Piepow/pure/blob/c0fdc006f2ed6b03ea8c801de441830200004da9/pure.zsh#L156).

Turns out this could be a problem in Pure as well (in the situation where the preprompt length is equal to COLUMNS), so thanks for reporting.

**Comment by mafredri** [comment] 2018-01-06 15:38
After a bit more investigating, it turns out this problem is triggered in Pure when the preprompt is exactly `$COLUMNS` wide and the async task adds something to the preprompt so that it's longer (e.g. dirty indicator turns preprompt into `$COLUMNS+1`).

I'm reopening this until this can be fixed in Pure.

**Comment by mafredri** [comment] 2018-01-06 16:50
It looks like the issue can only be triggered when `preprompt length == COLUMNS`. It doesn't matter how many async updates are done to the prompt. Even a single one will trigger the issue when length was COLUMNS and the new preprompt is `COLUMNS + N`.

This is not reproducible on zsh 5.3.1 so it seems like a regression in ZLE. We should report this to the zsh-workers mailing list. Would be good to have a minimal repro.

**Comment by Piepow** [comment] 2018-01-15 04:01
Thanks for your work. Unfortunately, I can't help you much with this, since I am not familiar with pure and zsh/bash scripting in general. I should also probably let you know that this is no longer an urgent problem for me, since I am using a different setup now.

**Comment by mafredri** [comment] 2018-04-22 10:55
I've forgotten how to reproduce this issue. At least it's not reproducible with stock Pure 1.7.0 and zsh 5.5, closing.

**Closed by mafredri** 2018-04-22 10:55 UTC
