### ISSUE TITLE
I'm getting "illegal character: \" 

### ISSUE THREAD

**Issue by loiccoyle** [sindresorhus/pure#420] opened 2018-07-21 22:42 UTC
### General information

- Pure version: 1.7.0
- ZSH version: 5.4.2
- Terminal program & version: termite v13-11-g3e2c10f
- Operating system: Ubuntu 18.04
- ZSH framework: nothing, just zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

Tested and reproduced on xfce4-terminal.

I've installed it manually, just zsh and pure prompt.

### Problem description
From time to time, I get the following error : "prompt_pure_async_callback:84: bad math expression: illegal character: \" I did some digging and I found a few people have had this error or similar when in a git repo, and to my understanding this was fixed. I get this error often after when I leave vim, or other command line programs. But it also happens, seemingly randomly.

I just figured out that if I refresh i3, the next command will be preceded by the error message.
### Reproduction steps

1. Stay in vim for a while then exit, it usually spits out the error 
2. Refresh i3, type enter in terminal

### My `.zshrc`:

autoload -U promptinit; promptinit
prompt pure

**Comment by mafredri** [comment] 2018-07-24 15:38
Does switching to pure `master` branch help? If not, are you using `pinentry` or some other interactive password prompt for ssh/git connections?

**Comment by mehalter** [comment] 2018-07-24 16:10
I am getting the same behavior on `master` branch, also I am not using any `pinentry` for interactive password prompts. I am also getting this message no matter what folder I am in, git or not.

```
~
❯
prompt_pure_async_callback:84: bad math expression: illegal character: \
~
❯
```

**Comment by mafredri** [comment] 2018-07-24 16:14
@mehalter and are you using the exact same setup as @loiccoyle? Zsh version, etc?

You should definitely not be seeing such messages outside of git folders.

**Comment by mehalter** [comment] 2018-07-24 16:21
I have 2 machines on my now and I can replicate the error on both. I have a 3rd that also has this error, but not on me so I can't give specific setup details. The two setups are

# Desktop
- Pure: `master`
- ZSH version: 5.1.1
- Terminal program & version: urxvt v9.21
- Operating system: Ubuntu 16.04
- ZSH framework: nothing, just zsh

# Laptop
- Pure: `master`
- ZSH version: 5.5.1
- Terminal program & version: urxvt v9.22
- Operating system: Arch - up to date
- ZSH framework: nothing, just zsh

Also this is happening for me in any folder.

Like @loiccoyle said

## Reproduction

- Stay in vim for a while then exit, it usually spits out the error
- Refresh i3, type enter in terminal

**Comment by mehalter** [comment] 2018-07-24 16:22
Also it does happen seemingly randomly like he said leaving vim or running programs that run for a while, but you can reproduce it instantly by refreshing i3 and pressing enter in a terminal.

**Comment by mehalter** [comment] 2018-07-24 16:33
I don't think I see any error before or after in the pure state / async buffer. Here I ran it 2 times before and after refreshing i3. I tried to label it clearly with lines `##=== ... ===##`. After running it the first time after refreshing it did return an error.

```~/Documents
❯ pwd; typeset -p prompt_pure_vcs_info; typeset -p ASYNC_PROCESS_BUFFER
/home/micah/Documents
typeset -A prompt_pure_vcs_info
prompt_pure_vcs_info=( branch '' top '' )
typeset -A ASYNC_PROCESS_BUFFER
ASYNC_PROCESS_BUFFER=( prompt_pure '' )

~/Documents
❯ pwd; typeset -p prompt_pure_vcs_info; typeset -p ASYNC_PROCESS_BUFFER
/home/micah/Documents
typeset -A prompt_pure_vcs_info
prompt_pure_vcs_info=( branch '' top '' )
typeset -A ASYNC_PROCESS_BUFFER
ASYNC_PROCESS_BUFFER=( prompt_pure '' )

##=== Refresh i3 ===##
~/Documents
❯ pwd; typeset -p prompt_pure_vcs_info; typeset -p ASYNC_PROCESS_BUFFER
/home/micah/Documents
typeset -A prompt_pure_vcs_info
prompt_pure_vcs_info=( branch '' top '' )
typeset -A ASYNC_PROCESS_BUFFER
ASYNC_PROCESS_BUFFER=( prompt_pure '' )

##=== I didn't press enter here, it did this on its own ===###
~/Documents
❯ 
prompt_pure_async_callback:84: bad math expression: illegal character: \
~/Documents
❯ pwd; typeset -p prompt_pure_vcs_info; typeset -p ASYNC_PROCESS_BUFFER
/home/micah/Documents
typeset -A prompt_pure_vcs_info
prompt_pure_vcs_info=( branch '' top '' )
typeset -A ASYNC_PROCESS_BUFFER
ASYNC_PROCESS_BUFFER=( prompt_pure '' )

~/Documents
❯ 
```

**Comment by mafredri** [comment] 2018-07-24 16:41
Ah, I think I see what's wrong. Your version of zsh-async is probably outdated, can you confirm if 1.6.0 is the one in use or not? Older versions of zsh-async did not provide a 6th argument to the callback, resulting in `next_pending` being empty, thus triggering a bad math expression; sorry I didn't see it sooner.

**Comment by mehalter** [comment] 2018-07-24 16:51
I am on the `master` branch of zsh-async on my machines. These lines are in my version of async.zsh

```
#
# zsh-async
#
# version: 1.6.0
# author: Mathias Fredriksson
# url: https://github.com/mafredri/zsh-async
#
```

**Comment by mafredri** [comment] 2018-07-24 16:53
Could you check your entire fpath to make sure there aren't any others?

```
for f in $^fpath/async; do [[ -e $f ]] && ls -lha $f; done
```

**Comment by mehalter** [comment] 2018-07-24 16:59
Hm, I don't see any others except for the one `zsh-async` instance

**Comment by loiccoyle** [comment] 2018-07-24 17:34
Hi guys, thanks for the help ! So no I'm not using any interactive password prompts, and yes I am using the master branch. I ran before and after the error and same as @mehalter  I'm not getting a change in the output :


❯ pwd; typeset -p prompt_pure_vcs_info; typeset -p ASYNC_PROCESS_BUFFER
/home/lcoyle
typeset -A prompt_pure_vcs_info=( branch '' top '' )
typeset -A ASYNC_PROCESS_BUFFER=( prompt_pure '' )

~
❯ 

~
❯ 
prompt_pure_async_callback:84: bad math expression: illegal character: \
~
❯ pwd; typeset -p prompt_pure_vcs_info; typeset -p ASYNC_PROCESS_BUFFER
/home/lcoyle
typeset -A prompt_pure_vcs_info=( branch '' top '' )
typeset -A ASYNC_PROCESS_BUFFER=( prompt_pure '' )

I checked the version of async and indeed I was outdated, I went and updated to 1.6.0 but I'm still getting the error. I don't see any other instance of async either.

**Comment by mafredri** [comment] 2018-07-25 20:32
I wonder if you could be hitting this line in `zsh-async`: [async.zsh#L249](https://github.com/mafredri/zsh-async/blob/6d0f41b8e3812abfeb881df9f39af373e3ba822e/async.zsh#L249). I see I've forgotten to add the 6th parameter there.

Let's try to debug this a bit, could you run this in your terminals and try to reproduce the issue:

```zsh
prompt_pure_async_callback2() {
    local -a args=("$@")
    typeset -p args; print
    prompt_pure_async_callback "$@"
}
ASYNC_CALLBACKS[prompt_pure]=prompt_pure_async_callback2
```

What does `args` look like when you're encountering the errors?

**Comment by loiccoyle** [comment] 2018-07-25 20:36
With no error, it looks like this : 
typeset -a args=( prompt_pure_async_vcs_info 0 'branch '\'\'' top '\'\' 0.0506784916 '' 0 )

When the error occurs it becomes :
typeset -a args=( async 1 '' 0 'async_process_results:42: error: bad format, got 89 items ($'\''\033'\''\]4' '\;' 0 '\;' '\#09100f$'\''\033'\''$'\''\033'\''\]4' '\;' 1 '\;' '\#3A4D45$'\''\033'\''$'\''\033'\''\]4' '\;' 2 '\;' '\#1F634D$'\''\033'\''$'\''\033'\''\]4' '\;' 3 '\;' '\#266F50$'\''\033'\''$'\''\033'\''\]4' '\;' 4 '\;' '\#398530$'\''\033'\''$'\''\033'\''\]4' '\;' 5 '\;' '\#5F942E$'\''\033'\''$'\''\033'\''\]4' '\;' 6 '\;' '\#8EA93A$'\''\033'\''$'\''\033'\''\]4' '\;' 7 '\;' '\#c5ce9c$'\''\033'\''$'\''\033'\''\]4' '\;' 8 '\;' '\#89906d$'\''\033'\''$'\''\033'\''\]4' '\;' 9 '\;' '\#3A4D45$'\''\033'\''$'\''\033'\''\]4' '\;' 10 '\;' '\#1F634D$'\''\033'\''$'\''\033'\''\]4' '\;' 11 '\;' '\#266F50$'\''\033'\''$'\''\033'\''\]4' '\;' 12 '\;' '\#398530$'\''\033'\''$'\''\033'\''\]4' '\;' 13 '\;' '\#5F942E$'\''\033'\''$'\''\033'\''\]4' '\;' 14 '\;' '\#8EA93A$'\''\033'\''$'\''\033'\''\]4' '\;' 15 '\;' '\#c5ce9c$'\''\033'\''$'\''\033'\''\]10' '\;' '\#c5ce9c$'\''\033'\''$'\''\033'\''\]11' '\;' '\#09100f$'\''\033'\''$'\''\033'\''\]12' '\;' '\#c5ce9c$'\''\033'\''$'\''\033'\''\]13' '\;' '\#c5ce9c$'\''\033'\''$'\''\033'\''\]17' '\;' '\#c5ce9c$'\''\033'\''$'\''\033'\''\]19' '\;' '\#09100f$'\''\033'\''$'\''\033'\''\]4' '\;' 232 '\;' '\#09100f$'\''\033'\''$'\''\033'\''\[s$'\''\033'\''\[1000H$'\''\033'\''\[8m$'\''\033'\''\]708' '\;' '\#09100f$'\''\033'\''$'\''\033'\''\[u$'\''\033'\''\]13' '\;' '\#c5ce9c$'\''\033'\''prompt_pure_async_vcs_info' 0 'branch\ \'\''\'\''\ top\ \'\''\'\' 0.0420277119 \'\'')' )

**Comment by mafredri** [comment] 2018-07-25 20:46
@loiccoyle you don't happen to recognize those hex codes from somewhere? Can you try searching for them? That does look like something interactive spawning inside the async worker but no idea what or why.

Can you reproduce the issue with a minimal zshrc (only Pure), I'm guessing there's more to your zshrc than you posted in this issue:

```zsh
zsh -f  # loads zsh without your zshrc
% autoload -Uz promptinit; promptinit
% fpath+=(/path/to/{prompt_pure_setup,async})
% prompt pure
```

**Comment by loiccoyle** [comment] 2018-07-25 21:09
Those hex values are the colors of the terminal, they are set by pywal if that helps. I can indeed reproduce the error in the same way with your commands. (I think the fpath+=(/path/to/{prompt_pure_setup,async}) needs to be before the autoload -Uz promptinit; promptinit command.)

**Comment by mafredri** [comment] 2018-07-26 06:49
Can you disable `pywal` and still reproduce the error? I don't really know anything about it but it seems like the most likely culprit, considering the async worker output.

> I think the fpath+=(/path/to/{prompt_pure_setup,async}) needs to be before the autoload -Uz promptinit; promptinit command.

You're right, fixed :).

**Comment by loiccoyle** [comment] 2018-07-26 09:12
Indeed ! disabling pywal does fix the issue, I will play around with it some more when I am free.

**Comment by mafredri** [comment] 2018-07-26 10:39
Great, we found the culprit :)! If we knew more of how pywal hooks into the shell / terminal we might be able to prevent it from happening in zsh-async.

@mehalter do you also use `pywal`? Maybe something similar that is running / causing output in the async worker?

**Comment by loiccoyle** [comment] 2018-07-26 17:57
I've been doing some snooping and pywal straight writes the colour escape sequences to /dev/pts/ to update the colours of all open terminals. I don't know if this helps.

**Comment by mafredri** [comment] 2018-08-06 15:13
Thanks for reporting back your findings @loiccoyle.

I've been thinking about potential solutions / workarounds to this, and while I haven't thought of a way to fix it entirely, I think I might have a way to improve upon it.

First off, I've released v1.6.2 of `zsh-async` which should take care of the `bad math expression` errors. **However**, this alone is not enough to prevent `pywal` from messing with the async worker. I've created a null-prefix: branch https://github.com/mafredri/zsh-async/pull/28 which should minimize the disturbance caused by `pywal`, would appreciate if you @loiccoyle and @mehalter could try it out!

Here's why v1.6.2 alone is not enough:

1. Write to async worker `print -n test >/dev/pts/1`
2. The next async result will be identified with a `test` prefix (e.g. `prompt_pure_async_vcs_info` -> `testprompt_pure_async_vcs_info`)
3. Pure doesn't recognize the test prefix command and ignores it

**Comment by mehalter** [comment] 2018-08-06 18:32
I have switched to this `null-prefix` branch and I can confirm I am no longer getting `bad math expression` errors.

**Comment by loiccoyle** [comment] 2018-08-06 19:08
Same here ! No bad math expression errors, well done @mafredri !

**Comment by mafredri** [comment] 2018-08-12 10:03
Great, thanks for testing both of you! I would still love to know what the output from the previous test is with the `null-prefix` branch, if you could repeat the test @loiccoyle or @mehalter, it would be much appreciated. (I'm thinking about the replaced callback test from https://github.com/sindresorhus/pure/issues/420#issuecomment-407885812.)

**Comment by loiccoyle** [comment] 2018-08-12 15:44
Here you go ! 
When I do the usual steps to trigger the error, the output is:
typeset -a args=( async 1 '' 0 'async_process_results:47: error: bad format, got 85 items ($'\''\033'\''\]4\ \;\ 0\ \;\ \#02022E$'\''\033'\''$'\''\033'\''\]4\ \;\ 1\ \;\ \#034A8F$'\''\033'\''$'\''\033'\''\]4\ \;\ 2\ \;\ \#095BA8$'\''\033'\''$'\''\033'\''\]4\ \;\ 3\ \;\ \#0269B7$'\''\033'\''$'\''\033'\''\]4\ \;\ 4\ \;\ \#4349A6$'\''\033'\''$'\''\033'\''\]4\ \;\ 5\ \;\ \#0378C7$'\''\033'\''$'\''\033'\''\]4\ \;\ 6\ \;\ \#9A6CB1$'\''\033'\''$'\''\033'\''\]4\ \;\ 7\ \;\ \#78bce2$'\''\033'\''$'\''\033'\''\]4\ \;\ 8\ \;\ \#54839e$'\''\033'\''$'\''\033'\''\]4\ \;\ 9\ \;\ \#034A8F$'\''\033'\''$'\''\033'\''\]4\ \;\ 10\ \;\ \#095BA8$'\''\033'\''$'\''\033'\''\]4\ \;\ 11\ \;\ \#0269B7$'\''\033'\''$'\''\033'\''\]4\ \;\ 12\ \;\ \#4349A6$'\''\033'\''$'\''\033'\''\]4\ \;\ 13\ \;\ \#0378C7$'\''\033'\''$'\''\033'\''\]4\ \;\ 14\ \;\ \#9A6CB1$'\''\033'\''$'\''\033'\''\]4\ \;\ 15\ \;\ \#78bce2$'\''\033'\''$'\''\033'\''\]10\ \;\ \#78bce2$'\''\033'\''$'\''\033'\''\]11\ \;\ \#02022E$'\''\033'\''$'\''\033'\''\]12\ \;\ \#78bce2$'\''\033'\''$'\''\033'\''\]13\ \;\ \#78bce2$'\''\033'\''$'\''\033'\''\]17\ \;\ \#78bce2$'\''\033'\''$'\''\033'\''\]19\ \;\ \#02022E$'\''\033'\''$'\''\033'\''\]4\ \;\ 232\ \;\ \#02022E$'\''\033'\''$'\''\033'\''\[s$'\''\033'\''\[1000H$'\''\033'\''\[8m$'\''\033'\''\]708\ \;\ \#02022E$'\''\033'\''$'\''\033'\''\[u$'\''\033'\''\]13\ \;\ \#78bce2$'\''\033'\'')' 1 )
Hope this helps !

**Comment by mafredri** [comment] 2018-08-12 15:59
That's perfect, exactly what I hoped to see. Thanks @loiccoyle! It's still not bulletproof but it should be extremely hard for `pywal` to interfere with the async worker now (requires impeccable timing). And there should be no more instances of bad math expression even if `pywal` does interfere (for better or worse).

I've merged the branch into `zsh-async` master, I'll look to make a new release of async and Pure in the coming days 😄.

**Comment by loiccoyle** [comment] 2018-08-12 16:02
Sounds good, you're welcome mate, thanks for the great prompt ! Good work !

**Closed** 2018-08-20 09:53 UTC
