### ISSUE TITLE
Option to set different symbol for error prompt

### ISSUE THREAD

**Issue by erusev** [sindresorhus/pure#456] opened 2019-01-06 13:17 UTC
As the readme states:

> Prompt character turns red if the last command didn't exit with 0.

The problem is that the regular prompt is in magenta and magenta and red are too similar and as a result, it's hard to distinguish regular prompt from error prompt.

An option to set a different symbol for error prompt would solve this. People could set it to "×" or "✖" and have an easier time distinguishing the prompt states.

**Comment by mafredri** [comment] 2019-01-21 17:41
Duplicate of #443.

**Closed by mafredri** 2019-01-21 17:41 UTC
