### ISSUE TITLE
Weird command repetition

### ISSUE THREAD

**Issue by victorronnow** [sindresorhus/pure#354] opened 2017-10-11 13:08 UTC
### General information

- Pure version: 5.4.2
- ZSH version: 5.4.1
- Terminal program & version: Hyper 1.4.8
- Operating system: macOS Sierra 10.12.6
- ZSH framework: oh-my-zsh

### Problem description
There is this weird command repetition when using auto-completion.
![skaermbillede 2017-10-11 kl 14 49 20](https://user-images.githubusercontent.com/17050767/31442073-82621510-ae95-11e7-9798-53e12055e054.png)

### Reproduction steps

1. Write command then navigate through files.
2. Hit tab (autocompletion)
3. The command is shown to times.

**Comment by sindresorhus** [comment] 2017-10-11 15:36
You installed Pure using this method: https://github.com/sindresorhus/pure#oh-my-zsh Right? If not. Try doing that.

**Comment by mafredri** [comment] 2017-10-31 19:51
If you followed sindresorhus instructions and the issue is still present, this might be a problem with Hyper as concluded in https://github.com/sindresorhus/pure/issues/248.

You can try to set `PURE_PROMPT_SYMBOL='>'` or change font and see if the problem goes away.

**Comment by mafredri** [comment] 2017-12-01 22:49
Closing due to age/lack of updates. Feel free to re-open if this is still an issue.

**Closed by mafredri** 2017-12-01 22:49 UTC

**Comment by niklaas** [comment] 2018-10-09 18:20
I run into the same issue. Changing the prompt symbol to '>' doesn't help.

**Comment by mafredri** [comment] 2018-10-12 09:29
@niklaas happy to hear, and thanks for reporting back! This would be good material for a troubleshooting section/document.
